CREATE TABLE IF NOT EXISTS prazos (
  id SERIAL PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  data_prazo TIMESTAMP NOT NULL,
  observacoes TEXT,
  licitacao_id INTEGER REFERENCES licitacoes(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 